version = 0.1

[default.deploy.parameters]
stack_name = "aleenas-cuisine-backend"
resolve_s3 = true
s3_prefix = "aleenas-cuisine-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "FunctionAlreadyExists=\"True\""

[default.global.parameters]
region = "ap-south-1"
