version = 0.1

[dev.deploy.parameters]
stack_name = "aleenascuisine-dev"
s3_bucket = "aleenascuisine-sam-artifacts" # <-- This tells SAM to use your bucket
confirm_changeset = true
disable_rollback = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Env=\"dev\" AppPrefix=\"aleenascuisine-dev\""
image_repositories = []

[dev.global.parameters]
region = "ap-south-1"

[prod.deploy.parameters]
stack_name = "aleenascuisine-prod"
s3_bucket = "aleenascuisine-sam-artifacts" # <-- This tells SAM to use your bucket
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Env=\"prod\" AppPrefix=\"aleenascuisine-prod\""
image_repositories = []

[prod.global.parameters]
region = "ap-south-1"